import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeNavbar from '../components/HomeNavbar'
import HomeBody from '../components/HomeBody'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TeamPod Finance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeNavbar />
      {/* <HomeBody /> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <b style={{color: "blue"}}>TeamPod Finance</b>
          {/* <a href="https://nextjs.org"></a> */}
        </h1>

        <p className={styles.description}>
          {/* <p style={{fontFamily: "Sans-Serif"}}> */}
            Closely connecting the world financially with protected team modeled community safe financing method!
            {/* </p> */}
          {/* Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Join A Team &rarr;</h2>
            <p>Find a TeamPod to join and enjoy a private socio-economic community.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Create A Team &rarr;</h2>
            <p>Create a Team and invite team members to form a secure financial savings club as Finance Pods in a socio-economic community.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>LP Funding &rarr;</h2>
            <p>Join an investment pool and invest your money with a 4% interest to be made by providing credit funds to secure TeamPod savings members.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
