import Head from 'next/head'
import Image from 'next/image'
 import Link from 'next/link'
// import { Link } from "react-router-dom";
import styles from '../styles/Home.module.css'
import HomeNavbar from '../components/HomeNavbar'

export default function JoinATeam() {

    return (
        <div className={styles.container}>
      <Head>
        <title>TeamPod Finance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeNavbar />
      {/* <HomeBody /> */}

      <main className={styles.main}>
        {/* <h2 className={styles.title}>
          Select a savings <b style={{color: "blue"}}>TeamPod</b> and Stake! */}
          {/* <a href="https://nextjs.org"></a> */}
        {/* </h2> */}
        <input
        className={styles.search}
        // onChange={onChange}
        //onFocus={onFocus}
        placeholder='Search Teams'
        type='text'
        //value={query}
      />

        <p className={styles.description}>
          {/* <p style={{fontFamily: "Sans-Serif"}}> */}
            {/* Closely connecting the world financially with protected team modeled community safe financing method! */}
            {/* </p> */}
          {/* Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
          <a href='/' className={styles.card}>
            <h2>Jab Pod</h2>
                {/* &rarr; */}
            <p>Stake is $200 per month. Pod size limit is 20 with two team members as earners each month.</p>
          </a>

          <a href="/" className={styles.card}>
            <h2>Yop Pod</h2>
                 {/* &rarr; */}
            <p>Stake is $700 per month. Pod size limit is 30 with 5 team members as earners each month.</p>
          </a>

          <a
             href="/"
            className={styles.card}
          >
            <h2>Quash Pod</h2>
                {/* &rarr; */}
            <p>Stake is $2000 per month. Pod size limit is 15 with 2 team members as earners each month.</p>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h2>Fil Pod</h2>
                {/* &rarr; */}

            <p>
            Stake is $5000 per month. Pod size limit is 20 with 6 team members as earners each month.
            </p>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h2>i Pod</h2>
                {/* &rarr; */}

            <p>
            Stake is $7000 per month. Pod size limit is 50 with 5 team members as earners each month.
            </p>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h2>Lt Pod</h2>
                {/* &rarr; */}

            <p>
            Stake is $10,000 per month. Pod size limit is 50 with 5 team members as earners each month.
            </p>
          </a>
          <a
            href="/"
            className={styles.card}
          >
            <h2>Gu Pod</h2>
                {/* &rarr; */}

            <p>
            Stake is $3000 per month. Pod size limit is 20 with 6 team members as earners each month.
            </p>
          </a>
          <a
            href="/"
            className={styles.card}
          >
            <h2>Si Pod</h2>
                {/* &rarr; */}

            <p>
            Stake is $15,000 per month. Pod size limit is 20 with 2 team members as earners each month.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/Tpod.png" alt=" Logo" width={80} height={30} />
          </span>
        </a>
      </footer>
    </div>
    )
}
